# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- dev

resources:
- repo: self

variables:
  imageName: 'image-$(Build.Repository.Name):$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image & Deploy
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'ServiceConnection-Manual'
        azureContainerRegistry: '{"loginServer":"danbtestazure.azurecr.io", "id" : "/subscriptions/ab034428-2882-4cf3-9862-dcbf9d5e3795/resourceGroups/test-resource-group/providers/Microsoft.ContainerRegistry/registries/danbtestazure"}'
        action: 'Build an image'
        dockerFile: 'Dockerfile'
        imageName: '$(imageName)'
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'ServiceConnection-Manual'
        azureContainerRegistry: '{"loginServer":"danbtestazure.azurecr.io", "id" : "/subscriptions/ab034428-2882-4cf3-9862-dcbf9d5e3795/resourceGroups/test-resource-group/providers/Microsoft.ContainerRegistry/registries/danbtestazure"}'
        action: 'Push an image'
        imageName: '$(imageName)'
    - task: AzureWebAppContainer@1
      displayName: 'Deploy: dan-docker-dev'
      inputs:
        azureSubscription: 'ServiceConnection-Manual'
        appName: 'dan-docker-dev'
        containers: 'danbtestazure.azurecr.io/$(imageName)'
      condition: eq(variables['Build.SourceBranchName'], 'dev')
    - task: AzureWebAppContainer@1
      displayName: 'Deploy: dan-docker-qa'
      inputs:
        azureSubscription: 'ServiceConnection-Manual'
        appName: 'dan-docker-qa'
        containers: 'danbtestazure.azurecr.io/image-$(Build.Repository.Name):$(Build.SourceBranchName)-$(Build.BuildId)'
      condition: eq(variables['Build.SourceBranchName'], 'main')



    


